MODWRKFLOW-2: Create DTO/Entity implementations of a the workflow interface.
folio-org/mod-workflow pull request #75
Opened 2024-01-10 15:42 UTC by kaladay

Resolves: [MODWRKFLOW-2](https://issues.folio.org/browse/MODWRKFLOW-2)

### Purpose
Provide and use DTOs rather than direct **Entities** when transmitting model data.
Add and use Lombok to simplify the code.

### Approach

#### Restructure Enumerations
Separate the enumerations from the models with the goal of helping make managing the different models somewhat easier.

#### Add and use Lombok
The methods are extracted into interfaces and have their interfaces prefixed with `Has`.
These are placed under the `has` directory.
There is a `has/common` directory (for lack of a better name) for interfaces that are specific to a given model.

The methods that are found to be used in multiple models have been provided in their own `Has` interface.
I attempted to break out the `Has` interfaces into groups of purpose, such as `HasVersioning`.
These could then support multiple methods that would be always grouped together.
The grouping of everything and how they should be group is not entirely clear at this point and so I opted to have most of the `Has` class be single purpose.
The `Has` `Common` interfaces are catch-all for a given model that is not broken out.
These may be changed in the future once the design is better hashed out.
Hashing this it out is considered out of scope.

This commit maintains the synthetic functions and keeps them on the model.
For an example see `hasCardinalityExpression()`.
This will need to be moved out into a DTO class in a subsequent commit.

#### Adding DTOs
The **Workflow** DTO and related are added.

The DTOs are used when fetching the data to reduce the data loaded from the database, such as with `WorkflowOperationDto`.
This required extracting out `HasDeploymentId` from `HasWorkflowCommon`.

### Additional Information

#### The "Has" Interfaces
There are `version` and `versionTag` properties.
It seems like these could be the same thing.
The `versionTag` is Camunda-specific.
This makes note of the situation and separates `version` under `Versioning` and `versionTag` remains as `VersionTag`.
Similarly, the `AsyncBefore` and `AsyncAfter` are also notable probably Camunda-specific properties.
There may be several more Camunda-specific properties.
Changing the behavior to remove Camunda-specific functionality is out of scope.

There is inconsistency in how properties are to be provided for connecting to services.
Some use a full URL and others have it broken up into parts.
This is either a previous design inconsistency or an inconsistency in Camunda.
The relevant `Has` interfaces are broken up to make room for fixing this at a later time.
Fixing the inconsistency is considered out of scope.

The password is broken out because ideally the password will not be specified all of the time.
This password should further be obfuscated.
The UI should not receive the password.
More work is needed to do this properly and that work is considered out of scope.
The only focus on the password is to separate it into its own `Has` interface.

Similarly, the username property is broken out.
It may or may not be moved into a combined property as I suggested in the comments or remain in its own separate `Has` interface for privacy and security considerations.
Deciding on this is out of scope.

#### RAML Files Rebuilt
This rebuilds the RAML files.
Rebuilding this revealed that some of the properties, namely `asyncBefore` and `asyncAfter`, are missing from the previous RAML files in some cases.

#### DTOs and Jackson
The Jackson handler as it is currently used cannot properly transfer an interface DTO (aka: a DTO Projection).
A concrete class is required.
For now, the **Workflow Entity** is directly used here.
This should be fine for the short term given that the entire **Workflow** is needed for these cases anyway.
Additional work is merited to better solve this.
Consider things like ModelMapper to assist with this.

The additional DTOs that should be created, like NodeDto, are not done due to an observed problem.
The `@JsonTypeInfo` and `@JsonSubTypes` using `deserializeAs` does not translate well into the interfaces that DTOs use.
This results in an invalid identifier and the **Workflow** cannot be activated.
This requires more research and work to determine a valid strategy to preserve the `getIdentifier()` needs but with an interface.

#### Lombok Getter and Setter
The `@Getter` and `@Setter` are used where `@Data` is preferred on the **Entities**.
Warnings and problems occur when the Had* interfaces exist on an **Entity** that has `@Data`.
To avoid this the more nuanced `@Getter` and `@Setter` are used for every property on the **Entity**.

2024-01-11 19:22 UTC, jeremythuff approved these changes

2024-01-11 23:34 UTC, wwelling commented on components/src/main/java/org/folio/rest/workflow/model/CompressFileTask.java
>  @Entity
Can we use [@Data](https://projectlombok.org/features/Data) here and avoid all the other annotations?

2024-01-11 23:37 UTC, wwelling requested changes
Can we use [@Data](https://projectlombok.org/features/Data) to avoid all the `@Getter` and `@Setter` annotations?

2024-01-11 23:43 UTC, wwelling commented
> Can we use [@Data](https://projectlombok.org/features/Data) to avoid all the `@Getter` and `@Setter` annotations?

<img width="404" alt="image" src="https://github.com/folio-org/mod-workflow/assets/144841721/e78607b6-33a9-4e90-953a-87a5fe39d78a">

1 [projectlombok.org](https://projectlombok.org/features/Data)
2 [stackoverflow.com](https://stackoverflow.com/questions/67378688/how-do-i-create-a-safe-lombok-jpa-entity)
3 [stackoverflow.com](https://stackoverflow.com/questions/40516058/lombok-data-and-builder-on-same-entity)
4 [dzone.com](https://dzone.com/articles/lombok-and-jpa-what-may-go-wrong)

2024-01-11 23:44 UTC, wwelling approved these changes

2024-01-12 02:24 UTC, jeremythuff commented
The use of the data annotation was explored but presented some complications. To keep the work in scope, we opted for the getter and setter annotations as they still reduced boilerplate code quite a bit.

2024-01-12 16:06 UTC, merged